import { Product, Address, Order, DeliverySlot, PaymentMethod, Recipe } from "../types";

// ─────────────────────────────────────────────────────────────────────────────
// VEGETABLES — सब्ज़ियाँ
// ─────────────────────────────────────────────────────────────────────────────
const VEGETABLES: Product[] = [
  {
    id: "p_tomato",
    name: "Organic Heirloom Tomato",
    nameHindi: "टमाटर",
    description: "Flawless, juicy, freshly harvested organic heirlooms with the stem attached. Perfect for salads, gravies, and sauces.",
    price: 80.00,
    unit: "1 kg",
    image: "/images/a1d3e64d43eac5c57a9fdb822a5b4fcc.jpg",
    category: "Vegetables",
    rating: 4.9,
    reviewCount: 128,
    isOrganic: true,
    isBestseller: true,
    nutritionBadge: "Rich in Lycopene",
    tags: ["Vegan", "Gluten Free", "No Pesticides"],
    inStock: true,
  },
  {
    id: "p_potato",
    name: "Farm Fresh Potato",
    nameHindi: "आलू",
    description: "Premium quality starchy potatoes, perfect for boiling, roasting, or making rich Indian curries and sabzis.",
    price: 30.00,
    unit: "1 kg",
    image: "/images/edc8bae03e403da32effc942b6ba6ac2.jpg",
    category: "Vegetables",
    rating: 4.8,
    reviewCount: 214,
    isBestseller: true,
    nutritionBadge: "High Potassium",
    tags: ["Vegan", "Gluten Free"],
    inStock: true,
  },
  {
    id: "p_onion",
    name: "Red Onions",
    nameHindi: "प्याज़",
    description: "Crisp and sharp red onions, an essential base ingredient for local Indian cuisines and gravies.",
    price: 40.00,
    unit: "1 kg",
    image: "/images/5021773a595f50c61af721494ed75084.jpg",
    category: "Vegetables",
    rating: 4.7,
    reviewCount: 98,
    nutritionBadge: "Quercetin Rich",
    tags: ["Vegan", "Gluten Free"],
    inStock: true,
  },
  {
    id: "p_cauliflower",
    name: "Fresh Cauliflower",
    nameHindi: "फूलगोभी",
    description: "Clean white cauliflower head loosely wrapped in green leaves. Freshly harvested and firm.",
    price: 60.00,
    unit: "1 pc",
    image: "/images/7d8bfda4102e389d2d64048dafd62208.jpg",
    category: "Vegetables",
    rating: 4.7,
    reviewCount: 67,
    nutritionBadge: "High Vitamin C",
    tags: ["Vegan", "Low Calorie"],
    inStock: true,
  },
  {
    id: "p_cucumber",
    name: "Fresh English Cucumber",
    nameHindi: "खीरा",
    description: "Cool, crunchy, seedless English cucumbers. Excellent for salads, raita, and detox water.",
    price: 40.00,
    unit: "1 kg",
    image: "/images/17a33c1248eb481e955b1e51627c4da5.jpg",
    category: "Vegetables",
    rating: 4.6,
    reviewCount: 44,
    nutritionBadge: "Hydrating",
    tags: ["Vegan", "Gluten Free", "Low Calorie"],
    inStock: true,
  },
  {
    id: "p_eggplant",
    name: "Fresh Purple Eggplant",
    nameHindi: "बैंगन",
    description: "Glossy deep-purple eggplant. Perfect for making traditional Baingan Bharta or stuffed brinjal.",
    price: 50.00,
    unit: "1 kg",
    image: "/images/77fe039834d4e76e55345e862f81590d.jpg",
    category: "Vegetables",
    rating: 4.5,
    reviewCount: 33,
    nutritionBadge: "Antioxidant Rich",
    tags: ["Vegan", "Gluten Free"],
    inStock: true,
  },
  {
    id: "p_zucchini",
    name: "Fresh Green Zucchini",
    nameHindi: "जुकिनी / हरी तोरई",
    description: "Tender, thin-skinned green zucchini squash, ideal for baking, stir-fries, or zoodles.",
    price: 80.00,
    unit: "500g",
    image: "/images/a72c0c6011c856914c0b3356903e5bf0.jpg",
    category: "Vegetables",
    rating: 4.6,
    reviewCount: 22,
    nutritionBadge: "Low Calorie",
    tags: ["Vegan", "Gluten Free"],
    inStock: true,
  },
  {
    id: "p_pumpkin",
    name: "Sweet Organic Pumpkin",
    nameHindi: "कद्दू",
    description: "Fleshy and golden sweet organic pumpkin. Perfect for rich soups, halwa, or curry.",
    price: 70.00,
    unit: "1 kg",
    image: "/images/01029f3d415e977c969aa6a29827887f.jpg",
    category: "Vegetables",
    rating: 4.7,
    reviewCount: 51,
    isOrganic: true,
    nutritionBadge: "Beta-Carotene Rich",
    tags: ["Vegan", "Organic"],
    inStock: true,
  },
  {
    id: "p_radish",
    name: "Crisp White Radish",
    nameHindi: "मूली",
    description: "Sharp and peppery white radishes (Mooli), ideal for parathas, salads and pickles.",
    price: 30.00,
    unit: "1 kg",
    image: "/images/8737084aa8f82643ab766025403bd1f9.jpg",
    category: "Vegetables",
    rating: 4.5,
    reviewCount: 29,
    nutritionBadge: "High Folate",
    tags: ["Vegan", "Gluten Free"],
    inStock: true,
  },
  {
    id: "p_greenbeans",
    name: "Tender Green Beans",
    nameHindi: "हरी बीन्स",
    description: "Freshly plucked, snapping tender green French beans. Loaded with nutrients and fiber.",
    price: 60.00,
    unit: "250g",
    image: "/images/d3a2f83058ef6f32f16c9a85f253ecf7.jpg",
    category: "Vegetables",
    rating: 4.7,
    reviewCount: 38,
    nutritionBadge: "High Fiber",
    tags: ["Vegan", "Gluten Free"],
    inStock: true,
  },
  {
    id: "p_peas",
    name: "Fresh Green Peas",
    nameHindi: "हरी मटर",
    description: "Sweet, tender green peas in their pods. Shell them fresh for maximum sweetness.",
    price: 80.00,
    unit: "500g",
    image: "/images/4fffaee012b2c5cd541a5eb924c46a00.jpg",
    category: "Vegetables",
    rating: 4.8,
    reviewCount: 74,
    nutritionBadge: "Protein Rich",
    tags: ["Vegan", "Gluten Free"],
    inStock: true,
  },
  {
    id: "p_corn",
    name: "Sweet Corn Cobs",
    nameHindi: "भुट्टा / मक्का",
    description: "Juicy, golden yellow sweet corn cobs. Excellent for boiling, grilling, or making corn chaat.",
    price: 40.00,
    unit: "Pack of 2",
    image: "/images/ab67adf4364a6f7902b921fb9ac2323c.jpg",
    category: "Vegetables",
    rating: 4.7,
    reviewCount: 62,
    nutritionBadge: "High Energy",
    tags: ["Vegan", "Gluten Free"],
    inStock: true,
  },
  {
    id: "p_okra",
    name: "Fresh Okra / Bhindi",
    nameHindi: "भिंडी",
    description: "Tender, slim, fresh green Okra pods. An essential element in daily Indian cooking.",
    price: 60.00,
    unit: "500g",
    image: "/images/9022808ff110e30b7652b09e31a3f76c.jpg",
    category: "Vegetables",
    rating: 4.7,
    reviewCount: 55,
    nutritionBadge: "High Vitamin K",
    tags: ["Vegan", "Gluten Free"],
    inStock: true,
  },
  {
    id: "p_mushroom",
    name: "Button Mushrooms",
    nameHindi: "मशरूम",
    description: "Fresh white button mushrooms, perfect for sautéing, pizza toppings, or adding to gravies.",
    price: 70.00,
    unit: "200g Pack",
    image: "/images/395033a6a9ea67cba8756ecb96a320ca.jpg",
    category: "Vegetables",
    rating: 4.7,
    reviewCount: 89,
    nutritionBadge: "Vitamin D Rich",
    tags: ["Vegan", "Gluten Free"],
    inStock: true,
  },
  {
    id: "p_ginger",
    name: "Fresh Ginger Root",
    nameHindi: "अदरक",
    description: "Pungent and spicy fresh ginger root, rich in antioxidants. Perfect for chai, curries and marinades.",
    price: 80.00,
    unit: "250g",
    image: "/images/296170bd6a7cc532aaa7c58826f3e7b9.jpg",
    category: "Vegetables",
    rating: 4.6,
    reviewCount: 41,
    nutritionBadge: "Anti-Inflammatory",
    tags: ["Vegan", "Gluten Free"],
    inStock: true,
  },
  {
    id: "p_leek",
    name: "Fresh Leeks",
    nameHindi: "लीक",
    description: "Sweet, onion-like green leeks, perfect for making gourmet potato-leek soups and stews.",
    price: 80.00,
    unit: "1 Bunch",
    image: "/images/781fe16320d6f95d555279f64f38204e.jpg",
    category: "Vegetables",
    rating: 4.7,
    reviewCount: 18,
    nutritionBadge: "Prebiotic Rich",
    tags: ["Vegan", "Gluten Free"],
    inStock: true,
  },
  {
    id: "p_celery",
    name: "Fresh Celery Stalks",
    nameHindi: "सैलरी / अजवायन के पत्ते",
    description: "Crisp and juicy green celery stalks. Perfect for healthy smoothies, soups and salads.",
    price: 90.00,
    unit: "1 Bunch",
    image: "/images/d75011737c8703caf0bfe4c25629a0f3.jpg",
    category: "Vegetables",
    rating: 4.6,
    reviewCount: 14,
    nutritionBadge: "Low Calorie",
    tags: ["Vegan", "Gluten Free"],
    inStock: true,
  },
  {
    id: "p_bellpepper",
    name: "Trio Bell Peppers",
    nameHindi: "शिमला मिर्च",
    description: "Crisp and colorful red, yellow, and green bell peppers in one pack. Rich in Vitamin C.",
    price: 120.00,
    unit: "Pack of 3",
    image: "/images/6b7ce3e711907e9936ff166d23517ddd.jpg",
    category: "Vegetables",
    rating: 4.8,
    reviewCount: 77,
    nutritionBadge: "High Vitamin C",
    tags: ["Vegan", "Gluten Free"],
    inStock: true,
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// FRUITS — फल
// ─────────────────────────────────────────────────────────────────────────────
const FRUITS: Product[] = [
  {
    id: "p_strawberry",
    name: "Sweet Strawberries",
    nameHindi: "स्ट्रॉबेरी",
    description: "Plump, juicy, and bright red hand-picked fresh strawberries in a box. Packed with sweetness and antioxidants.",
    price: 199.00,
    unit: "400g Box",
    image: "/images/1533569645ae988271341a4204ab1724.jpg",
    category: "Fruits",
    rating: 4.9,
    reviewCount: 193,
    isBestseller: true,
    nutritionBadge: "Antioxidant Rich",
    tags: ["Vegan", "Gluten Free"],
    inStock: true,
  },
  {
    id: "p_avocado",
    name: "Hass Avocados",
    nameHindi: "एवोकैडो",
    description: "Flawless Hass avocados with a rich, creamy interior. Perfect for fresh homemade guacamole or toast.",
    price: 240.00,
    unit: "Pack of 3",
    image: "/images/89caf15ee7737ed0ca52134825a70d89.jpg",
    category: "Fruits",
    rating: 4.7,
    reviewCount: 88,
    isOrganic: true,
    nutritionBadge: "Healthy Fats",
    tags: ["Vegan", "Keto Friendly"],
    inStock: true,
  },
  {
    id: "p_apple",
    name: "Royal Gala Apples",
    nameHindi: "सेब",
    description: "Crisp and sweet gala apples with a beautiful red blush. Freshly imported and carefully stored.",
    price: 180.00,
    unit: "1 kg",
    image: "/images/8f4eae051c1f8136206803e6ebea19a5.jpg",
    category: "Fruits",
    rating: 4.7,
    reviewCount: 115,
    isBestseller: true,
    nutritionBadge: "High Fiber",
    tags: ["Vegan", "Gluten Free"],
    inStock: true,
  },
  {
    id: "p_banana",
    name: "Premium Bananas",
    nameHindi: "केला",
    description: "Naturally ripened sweet yellow bananas. High energy and rich in potassium.",
    price: 60.00,
    unit: "1 Dozen",
    image: "/images/0b519088f41813a326fc34cdeaf72bc5.jpg",
    category: "Fruits",
    rating: 4.8,
    reviewCount: 201,
    isBestseller: true,
    nutritionBadge: "High Potassium",
    tags: ["Vegan", "Gluten Free"],
    inStock: true,
  },
  {
    id: "p_mango",
    name: "Alphonso Mangoes",
    nameHindi: "आम",
    description: "The King of Mangoes! Luscious, sweet, highly aromatic Alphonso mangoes from Ratnagiri.",
    price: 349.00,
    originalPrice: 420.00,
    unit: "Pack of 2",
    image: "/images/0c8d6198d49599cd93a741a89ed5b1cc.jpg",
    category: "Fruits",
    rating: 4.9,
    reviewCount: 174,
    isExotic: true,
    isBestseller: true,
    nutritionBadge: "High Vitamin A",
    tags: ["Seasonal", "Premium"],
    inStock: true,
  },
  {
    id: "p_dragonFruit",
    name: "Vibrant Dragon Fruit",
    nameHindi: "ड्रैगन फ्रूट",
    description: "Stunning exotic dragon fruit sliced in half to display white flesh loaded with black seeds.",
    price: 149.00,
    unit: "1 pc",
    image: "/images/63d7b4e5d1f514a4f378c485efcc9381.jpg",
    category: "Fruits",
    rating: 4.9,
    reviewCount: 62,
    isExotic: true,
    nutritionBadge: "Antioxidant Rich",
    tags: ["Exotic", "Vegan"],
    inStock: true,
  },
  {
    id: "p_grapes",
    name: "Seedless Green Grapes",
    nameHindi: "अंगूर",
    description: "Chilled, crunchy, seedless green grapes bursting with natural sweetness. Great as a snack or in fruit salads.",
    price: 120.00,
    unit: "500g Punnet",
    image: "/images/ca4a6882767b39267f756e0a9da37a83.jpg",
    category: "Fruits",
    rating: 4.6,
    reviewCount: 49,
    nutritionBadge: "Resveratrol Rich",
    tags: ["Vegan", "Gluten Free"],
    inStock: true,
  },
  {
    id: "p_orange",
    name: "Nagpur Oranges",
    nameHindi: "संतरा",
    description: "Juicy Nagpur oranges, bright and citrusy. Best known for their sweetness and easy peeling.",
    price: 80.00,
    unit: "1 kg",
    image: "/images/5a52e3f22a5fc468ce4d9c69d979764e.jpg",
    category: "Fruits",
    rating: 4.7,
    reviewCount: 83,
    nutritionBadge: "High Vitamin C",
    tags: ["Vegan", "Gluten Free"],
    inStock: true,
  },
  {
    id: "p_pomegranate",
    name: "Ruby Pomegranate",
    nameHindi: "अनार",
    description: "Large, jewel-red pomegranates bursting with sweet-tart juice. Known for exceptional heart health benefits.",
    price: 130.00,
    unit: "2 pcs",
    image: "/images/4bf5d32f621173558dfd9fcadd06a1f5.jpg",
    category: "Fruits",
    rating: 4.8,
    reviewCount: 56,
    nutritionBadge: "Heart Healthy",
    tags: ["Vegan", "Antioxidant"],
    inStock: true,
  },
  {
    id: "p_papaya",
    name: "Sweet Ripe Papaya",
    nameHindi: "पपीता",
    description: "Sun-ripened orange-fleshed papaya with a honey-sweet taste. Rich in papain enzyme for better digestion.",
    price: 60.00,
    unit: "1 pc (~800g)",
    image: "/images/11fe2de0db7a0bb03988b34a3675421a.jpg",
    category: "Fruits",
    rating: 4.6,
    reviewCount: 39,
    nutritionBadge: "Digestive Aid",
    tags: ["Vegan", "Gluten Free"],
    inStock: true,
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// ORGANIC — जैविक
// ─────────────────────────────────────────────────────────────────────────────
const ORGANIC: Product[] = [
  {
    id: "p_spinach",
    name: "Fresh Baby Spinach",
    nameHindi: "पालक",
    description: "Crisp, washed, and highly nutritious baby spinach leaves. Tied loosely, ready for salads or sautés.",
    price: 40.00,
    unit: "250g Bunch",
    image: "/images/9154e255b5f1ec4dc576a480aff96a09.jpg",
    category: "Organic",
    rating: 4.8,
    reviewCount: 122,
    isOrganic: true,
    isBestseller: true,
    nutritionBadge: "Rich in Iron",
    tags: ["Certified Organic", "Vegan"],
    inStock: true,
  },
  {
    id: "p_lettuce",
    name: "Crisp Green Lettuce",
    nameHindi: "सलाद पत्ता",
    description: "Dewy, fresh, green romaine lettuce head. Exceptional crunch and farm-to-table freshness.",
    price: 60.00,
    unit: "Head",
    image: "/images/3cda1265765585b9597913b723bfa897.jpg",
    category: "Organic",
    rating: 4.6,
    reviewCount: 47,
    isOrganic: true,
    nutritionBadge: "High Folate",
    tags: ["Certified Organic", "Vegan", "Low Calorie"],
    inStock: true,
  },
  {
    id: "p_carrot",
    name: "Organic Sweet Carrot",
    nameHindi: "गाजर",
    description: "Sweet, crunchy, freshly dug organic carrots. Ideal for salads, juices, halwa, or cooking.",
    price: 50.00,
    unit: "1 kg",
    image: "/images/38489e84315152fce0c0d1efafee6aa2.jpg",
    category: "Organic",
    rating: 4.8,
    reviewCount: 93,
    isOrganic: true,
    nutritionBadge: "Beta-Carotene Rich",
    tags: ["Certified Organic", "Vegan"],
    inStock: true,
  },
  {
    id: "p_cabbage",
    name: "Crisp Green Cabbage",
    nameHindi: "पत्तागोभी",
    description: "Dewy green cabbage head with thick leaves, packed with fiber. Great for stir-fries and salads.",
    price: 45.00,
    unit: "1 pc",
    image: "/images/fefa557fe22bab5a1e1742227485e7b6.jpg",
    category: "Organic",
    rating: 4.6,
    reviewCount: 38,
    isOrganic: true,
    nutritionBadge: "High Vitamin K",
    tags: ["Certified Organic", "Vegan"],
    inStock: true,
  },
  {
    id: "p_broccoli",
    name: "Organic Broccoli Florets",
    nameHindi: "ब्रोकोली",
    description: "Vibrant green organic broccoli crowns, exceptionally high in iron, calcium and antioxidants.",
    price: 90.00,
    unit: "250g Bunch",
    image: "/images/00fe39ffe39c3ffb7145091ec26c5b97.jpg",
    category: "Organic",
    rating: 4.8,
    reviewCount: 104,
    isOrganic: true,
    isBestseller: true,
    nutritionBadge: "Superfood",
    tags: ["Certified Organic", "Vegan", "Gluten Free"],
    inStock: true,
  },
  {
    id: "p_beetroot",
    name: "Organic Red Beetroot",
    nameHindi: "चुकंदर",
    description: "Sweet, earthy, and deep crimson beetroot bulbs. Promotes excellent blood health and immunity.",
    price: 50.00,
    unit: "1 kg",
    image: "/images/4250a5c5d28585cbaad4b5fa8a7cc108.jpg",
    category: "Organic",
    rating: 4.8,
    reviewCount: 71,
    isOrganic: true,
    nutritionBadge: "Nitrate Rich",
    tags: ["Certified Organic", "Vegan"],
    inStock: true,
  },
  {
    id: "p_turnip",
    name: "Organic Turnips",
    nameHindi: "शलजम",
    description: "Mild and sweet white-and-purple turnips, freshly picked from local organic soil.",
    price: 60.00,
    unit: "1 kg",
    image: "/images/a8449c8577fa8afbc9efbf6149ce31a5.jpg",
    category: "Organic",
    rating: 4.6,
    reviewCount: 21,
    isOrganic: true,
    nutritionBadge: "High Fiber",
    tags: ["Certified Organic", "Vegan"],
    inStock: true,
  },
  {
    id: "p_sweetpotato",
    name: "Organic Sweet Potato",
    nameHindi: "शकरकंद",
    description: "Starchy, sweet, and red-skinned organic sweet potatoes, fresh from certified local fields.",
    price: 50.00,
    unit: "1 kg",
    image: "/images/383d9385eb5c39cce958c55a7fe37061.jpg",
    category: "Organic",
    rating: 4.8,
    reviewCount: 58,
    isOrganic: true,
    nutritionBadge: "High Vitamin A",
    tags: ["Certified Organic", "Vegan", "Gluten Free"],
    inStock: true,
  },
  {
    id: "p_kale",
    name: "Organic Curly Kale",
    nameHindi: "केल पत्ता",
    description: "Earthy, organic curly kale leaves. Excellent superfood for green juices and Caesar salads.",
    price: 80.00,
    unit: "1 Bunch",
    image: "/images/ae2858f85758f2135e68f62230b19f2a.jpg",
    category: "Organic",
    rating: 4.8,
    reviewCount: 43,
    isOrganic: true,
    nutritionBadge: "Superfood",
    tags: ["Certified Organic", "Vegan"],
    inStock: true,
  },
  {
    id: "p_garlic",
    name: "Organic Garlic Bulbs",
    nameHindi: "लहसुन",
    description: "Aromatically rich, organic garlic bulbs with tight cloves. Perfect for sautéing and seasoning.",
    price: 120.00,
    unit: "250g",
    image: "/images/dc02f774ea8dea48f248c01148e9c11e.jpg",
    category: "Organic",
    rating: 4.8,
    reviewCount: 66,
    isOrganic: true,
    nutritionBadge: "Immune Booster",
    tags: ["Certified Organic", "Vegan", "Anti-Inflammatory"],
    inStock: true,
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// DAIRY — डेयरी
// ─────────────────────────────────────────────────────────────────────────────
const DAIRY: Product[] = [
  {
    id: "p_milk",
    name: "Premium Farm Fresh Milk",
    nameHindi: "ताजा दूध",
    description: "Rich, creamy, pasteurized whole milk bottled fresh from local organic dairies. No added preservatives.",
    price: 75.00,
    unit: "1 Litre",
    image: "/images/349e1cba22abafa031d6d28a50c2f74b.jpg",
    category: "Dairy",
    rating: 4.8,
    reviewCount: 162,
    isBestseller: true,
    nutritionBadge: "High Calcium",
    tags: ["Gluten Free", "Farm Fresh"],
    inStock: true,
  },
  {
    id: "p_paneer",
    name: "Fresh Organic Paneer",
    nameHindi: "पनीर",
    description: "Soft, white cottage cheese cubes made from organic cow milk. Ideal for curries, bhurji, and tikka.",
    price: 119.00,
    unit: "200g",
    image: "/images/c2e26730a5ec41cbe953c5d3d5f60b57.jpg",
    category: "Dairy",
    rating: 4.9,
    reviewCount: 197,
    isOrganic: true,
    isBestseller: true,
    nutritionBadge: "High Protein",
    tags: ["Certified Organic", "Gluten Free", "Vegetarian"],
    inStock: true,
  },
  {
    id: "p_curd",
    name: "Thick Fresh Curd",
    nameHindi: "दही",
    description: "Creamy, naturally set curd with high calcium content. Delicious, gut-friendly, and probiotic-rich.",
    price: 45.00,
    unit: "500g",
    image: "/images/6f3af931c71f34ee37afc21cfed550ec.jpg",
    category: "Dairy",
    rating: 4.7,
    reviewCount: 88,
    nutritionBadge: "Probiotic Rich",
    tags: ["Gluten Free", "Vegetarian"],
    inStock: true,
  },
  {
    id: "p_butter",
    name: "Salted Farm Butter",
    nameHindi: "मक्खन",
    description: "Rich, salted butter churned fresh from organic dairy cream. Melt-in-your-mouth taste for any cooking.",
    price: 55.00,
    unit: "100g",
    image: "/images/e39fc59fb9eb1deadd5976567041cfb5.jpg",
    category: "Dairy",
    rating: 4.8,
    reviewCount: 74,
    nutritionBadge: "Vitamin A Rich",
    tags: ["Gluten Free", "Farm Fresh"],
    inStock: true,
  },
  {
    id: "p_ghee",
    name: "Pure Desi Cow Ghee",
    nameHindi: "देसी घी",
    description: "Bilona-churned pure A2 desi cow ghee with a rich golden hue. The purest form of clarified butter.",
    price: 449.00,
    unit: "500ml Jar",
    image: "/images/1a57889280c41b4864ad1f1a666dc082.jpg",
    category: "Dairy",
    rating: 4.9,
    reviewCount: 211,
    isOrganic: true,
    isBestseller: true,
    nutritionBadge: "A2 Protein",
    tags: ["Certified Organic", "Gluten Free", "Premium"],
    inStock: true,
  },
  {
    id: "p_cheese",
    name: "Processed Cheese Slice",
    nameHindi: "चीज़ स्लाइस",
    description: "Perfectly melting processed cheese slices. Ideal for sandwiches, burgers, and pasta bakes.",
    price: 99.00,
    unit: "Pack of 10",
    image: "/images/2d59c326e4a7b11778d8583d9da52bbd.jpg",
    category: "Dairy",
    rating: 4.5,
    reviewCount: 53,
    nutritionBadge: "Calcium Rich",
    tags: ["Gluten Free", "Vegetarian"],
    inStock: true,
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// EXOTIC — विदेशी
// ─────────────────────────────────────────────────────────────────────────────
const EXOTIC: Product[] = [
  {
    id: "p_asparagus",
    name: "Tender Asparagus Spears",
    nameHindi: "शतावरी",
    description: "Ethereal, premium quality fresh green asparagus stalks. Perfect for pan searing with garlic and olive oil.",
    price: 199.00,
    unit: "250g Bunch",
    image: "/images/1c471c170d5adb58eb81ce870e483014.jpg",
    category: "Exotic",
    rating: 4.8,
    reviewCount: 35,
    isExotic: true,
    nutritionBadge: "Prebiotic Rich",
    tags: ["Exotic", "Vegan", "Gluten Free"],
    inStock: true,
  },
  {
    id: "p_brussels",
    name: "Brussels Sprouts",
    nameHindi: "छोटा पत्तागोभी",
    description: "Tiny cabbage-like Brussels sprouts. Roast them with olive oil and balsamic for a premium side dish.",
    price: 140.00,
    unit: "250g Pack",
    image: "/images/0d43bd266956242e69f029f6f4f8fdcc.jpg",
    category: "Exotic",
    rating: 4.7,
    reviewCount: 28,
    isExotic: true,
    nutritionBadge: "Vitamin K Rich",
    tags: ["Exotic", "Vegan"],
    inStock: true,
  },
  {
    id: "p_artichoke",
    name: "Globe Artichoke",
    nameHindi: "हाथीचोक",
    description: "Exotic globe artichokes, featuring soft, edible leaf bases and hearts. A gourmet experience.",
    price: 120.00,
    unit: "1 pc",
    image: "/images/ec3d4cdd4f00508b9831bd97680740ca.jpg",
    category: "Exotic",
    rating: 4.6,
    reviewCount: 16,
    isExotic: true,
    nutritionBadge: "Liver Support",
    tags: ["Exotic", "Vegan"],
    inStock: true,
  },
  {
    id: "p_bok_choy",
    name: "Baby Bok Choy",
    nameHindi: "चाइनीज पत्तागोभी",
    description: "Crisp, tender baby bok choy with crunchy stalks and mild leafy greens. A staple in Asian stir-fries.",
    price: 110.00,
    unit: "250g Pack",
    image: "/images/5499e799ce0e807de4dca54708d4a35a.jpg",
    category: "Exotic",
    rating: 4.7,
    reviewCount: 22,
    isExotic: true,
    nutritionBadge: "High Vitamin C",
    tags: ["Exotic", "Vegan", "Asian Cuisine"],
    inStock: true,
  },
  {
    id: "p_edamame",
    name: "Fresh Edamame",
    nameHindi: "हरी सोयाबीन",
    description: "Plump, vibrant green edamame pods lightly salted and blanched. A healthy protein-packed snack.",
    price: 130.00,
    unit: "200g Pack",
    image: "/images/8e4a14ef6b2791503253212a60227cba.jpg",
    category: "Exotic",
    rating: 4.6,
    reviewCount: 19,
    isExotic: true,
    nutritionBadge: "High Protein",
    tags: ["Exotic", "Vegan", "Gluten Free"],
    inStock: true,
  },
  {
    id: "p_physalis",
    name: "Cape Gooseberry",
    nameHindi: "रसभरी / केप गूसबेरी",
    description: "Sweet-tart golden cape gooseberries with a papery husk. A delicious exotic snack or garnish.",
    price: 180.00,
    unit: "125g Box",
    image: "/images/41e345edd9702f555fb57e933b4ad987.jpg",
    category: "Exotic",
    rating: 4.8,
    reviewCount: 14,
    isExotic: true,
    nutritionBadge: "Vitamin D Rich",
    tags: ["Exotic", "Vegan", "Rare"],
    inStock: true,
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// COMBINED MASTER PRODUCT LIST
// ─────────────────────────────────────────────────────────────────────────────
const MOCK_PRODUCTS: Product[] = [
  ...VEGETABLES,
  ...FRUITS,
  ...ORGANIC,
  ...DAIRY,
  ...EXOTIC,
];

// ─────────────────────────────────────────────────────────────────────────────
// AI SUGGESTED RECIPES
// ─────────────────────────────────────────────────────────────────────────────
const MOCK_RECIPES: Recipe[] = [
  {
    id: "r1",
    name: "Gourmet Shahi Paneer",
    description: "A rich, creamy Indian curry with melt-in-mouth cottage cheese paneer cubes simmered in a luscious tomato-onion gravy.",
    prepTime: "25 mins",
    difficulty: "Medium",
    image: "/images/c2e26730a5ec41cbe953c5d3d5f60b57.jpg",
    mainIngredientId: "p_paneer",
    ingredients: [
      { productId: "p_paneer", name: "Fresh Organic Paneer (पनीर)", quantity: "200g", price: 119 },
      { productId: "p_tomato", name: "Organic Heirloom Tomato (टमाटर)", quantity: "500g", price: 80 },
      { productId: "p_onion", name: "Red Onions (प्याज़)", quantity: "250g", price: 40 },
      { productId: "p_butter", name: "Salted Farm Butter (मक्खन)", quantity: "50g", price: 55 },
      { productId: "p_ginger", name: "Fresh Ginger Root (अदरक)", quantity: "20g", price: 80 },
    ],
  },
  {
    id: "r2",
    name: "Classic Creamy Guacamole",
    description: "An authentic, healthy Mexican avocado dip made with diced tomatoes, red onions, garlic, and fresh citrus notes.",
    prepTime: "10 mins",
    difficulty: "Easy",
    image: "/images/89caf15ee7737ed0ca52134825a70d89.jpg",
    mainIngredientId: "p_avocado",
    ingredients: [
      { productId: "p_avocado", name: "Hass Avocados (एवोकैडो)", quantity: "3 pcs", price: 240 },
      { productId: "p_tomato", name: "Organic Heirloom Tomato (टमाटर)", quantity: "150g", price: 80 },
      { productId: "p_onion", name: "Red Onions (प्याज़)", quantity: "100g", price: 40 },
      { productId: "p_garlic", name: "Organic Garlic Bulbs (लहसुन)", quantity: "10g", price: 120 },
    ],
  },
  {
    id: "r3",
    name: "Superfood Spinach Salad",
    description: "A quick, nutrient-packed salad combining crisp spinach leaves, sweet heirloom tomatoes, and Romaine lettuce.",
    prepTime: "8 mins",
    difficulty: "Easy",
    image: "/images/9154e255b5f1ec4dc576a480aff96a09.jpg",
    mainIngredientId: "p_spinach",
    ingredients: [
      { productId: "p_spinach", name: "Fresh Baby Spinach (पालक)", quantity: "250g", price: 40 },
      { productId: "p_tomato", name: "Organic Heirloom Tomato (टमाटर)", quantity: "300g", price: 80 },
      { productId: "p_lettuce", name: "Crisp Green Lettuce (सलाद पत्ता)", quantity: "1 head", price: 60 },
    ],
  },
  {
    id: "r4",
    name: "Aloo Tamatar Sabzi",
    description: "A classic North Indian comfort food stew made with boiled potatoes simmered in a spiced tomato gravy.",
    prepTime: "20 mins",
    difficulty: "Easy",
    image: "/images/edc8bae03e403da32effc942b6ba6ac2.jpg",
    mainIngredientId: "p_potato",
    ingredients: [
      { productId: "p_potato", name: "Farm Fresh Potato (आलू)", quantity: "500g", price: 30 },
      { productId: "p_tomato", name: "Organic Heirloom Tomato (टमाटर)", quantity: "300g", price: 80 },
      { productId: "p_onion", name: "Red Onions (प्याज़)", quantity: "150g", price: 40 },
      { productId: "p_ginger", name: "Fresh Ginger Root (अदरक)", quantity: "15g", price: 80 },
      { productId: "p_garlic", name: "Organic Garlic Bulbs (लहसुन)", quantity: "10g", price: 120 },
    ],
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// MOCK DATA — Addresses, Promos
// ─────────────────────────────────────────────────────────────────────────────
const MOCK_ADDRESSES: Address[] = [
  {
    id: "addr_1",
    label: "Home",
    name: "Karan Singh",
    street: "12 Green Valley Street",
    apartment: "Flat 3B",
    city: "New Delhi",
    zipCode: "110001",
    phone: "+91 98765 43210",
    isDefault: true,
    expressEligible: true,
  },
  {
    id: "addr_2",
    label: "Office",
    name: "Karan Singh",
    street: "45 Cyber Hub",
    apartment: "Block B, 5th Floor",
    city: "Gurugram",
    zipCode: "122002",
    phone: "+91 98765 43210",
    isDefault: false,
    expressEligible: false,
  },
];

const MOCK_PROMOS: { [code: string]: number } = {
  FRESH20: 20,
  ORGANIC10: 10,
  GREENFREE: 100,
};

// ─────────────────────────────────────────────────────────────────────────────
// API METHODS
// ─────────────────────────────────────────────────────────────────────────────
const delay = (ms: number = 800) => new Promise((resolve) => setTimeout(resolve, ms));

export const GreenGraceAPI = {
  getProducts: async (): Promise<Product[]> => {
    await delay(300);
    return [...MOCK_PRODUCTS];
  },

  getProductById: async (id: string): Promise<Product | null> => {
    await delay(200);
    const product = MOCK_PRODUCTS.find((p) => p.id === id);
    return product ? { ...product } : null;
  },

  getProductsByCategory: async (category: string): Promise<Product[]> => {
    await delay(200);
    if (category === "Organic") return MOCK_PRODUCTS.filter((p) => p.isOrganic);
    if (category === "Exotic") return MOCK_PRODUCTS.filter((p) => p.isExotic);
    return MOCK_PRODUCTS.filter((p) => p.category === category);
  },

  getAddresses: async (): Promise<Address[]> => {
    await delay(300);
    return [...MOCK_ADDRESSES];
  },

  getRecipes: async (): Promise<Recipe[]> => {
    await delay(400);
    return [...MOCK_RECIPES];
  },

  getRecipesByProductId: async (productId: string): Promise<Recipe[]> => {
    await delay(200);
    return MOCK_RECIPES.filter((recipe) =>
      recipe.ingredients.some((ingredient) => ingredient.productId === productId)
    );
  },

  verifyPromoCode: async (
    code: string
  ): Promise<{ success: boolean; discountPercent: number; message: string }> => {
    await delay(300);
    const normalizedCode = code.trim().toUpperCase();
    if (normalizedCode in MOCK_PROMOS) {
      return {
        success: true,
        discountPercent: MOCK_PROMOS[normalizedCode],
        message: `Promo code '${normalizedCode}' applied successfully!`,
      };
    }
    return {
      success: false,
      discountPercent: 0,
      message: "Invalid promo code. Please try again.",
    };
  },

  createOrder: async (orderData: Omit<Order, "id" | "createdAt" | "status">): Promise<Order> => {
    await delay(600);
    const orderId = `GG-${Math.floor(100000 + Math.random() * 900000)}`;
    return {
      ...orderData,
      id: orderId,
      status: "pending",
      createdAt: new Date().toISOString(),
    };
  },
};
